name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Publish Blazor app
        run: dotnet publish -c Release -o dist

      - name: Replace <base href> in dist/index.html
        run: |
          sed -i 's|<base href="/" />|<base href="/YeagerDotNet/" />|' dist/wwwroot/index.html
          cp dist/wwwroot/.nojekyll dist/wwwroot/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/wwwroot
