name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Publish Blazor app
        # ← run dotnet publish in the project folder
        working-directory: ./YeagerDotNet
        run: dotnet publish -c Release -o dist

      - name: Patch base href + include nojekyll
        # ← still in repo root by default,
        #    so reference the subfolder’s dist
        run: |
          sed -i 's|<base href="/" />|<base href="/YeagerDotNet/" />|' YeagerDotNet/dist/index.html
          cp YeagerDotNet/dist/.nojekyll YeagerDotNet/dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # ← publish the files you just built
          publish_dir: YeagerDotNet/dist
          publish_branch: gh-pages
