permissions:
  contents: write
  pages:    write

name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # ensure the GITHUB_TOKEN is available

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
      
      - name: Publish Blazor app
        working-directory: ./YeagerDotNet
        run: dotnet publish -c Release -o dist

      - name: Patch <base href> + include .nojekyll
        run: |
          sed -i 's|<base href="/" />|<base href="/YeagerDotNet/" />|' YeagerDotNet/dist/wwwroot/index.html
          # your .nojekyll was already in wwwroot, so publish will include it

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:   YeagerDotNet/dist/wwwroot
          publish_branch: gh-pages
